version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/batch'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/db'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/logger'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/packages/ui'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/docs/specs'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'npm'
    directory: '/docs/manual'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
