import { existsSync, readdirSync, readFileSync, rmSync, statSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Add header comment to relations.ts if it doesn't exist
const relationsPath = './src/relations.ts';
if (existsSync(relationsPath)) {
  const content = readFileSync(relationsPath, 'utf-8');

  // Check if header comment already exists
  if (!content.includes('Drizzle ORM relations definitions')) {
    const headerComment = `/**
 * Drizzle ORM relations definitions.
 *
 * This file is used to define relationships between tables using Drizzle's
 * relations API. If no relations are currently defined, this file may be
 * empty. Relations can be added here as needed when table relationships
 * are established.
 *
 * @example
 * \`\`\`typescript
 * import { relations } from "drizzle-orm/relations";
 * import { users, posts } from "./schema.js";
 *
 * export const usersRelations = relations(users, ({ one, many }) => ({
 *   posts: many(posts),
 * }));
 *
 * export const postsRelations = relations(posts, ({ one }) => ({
 *   author: one(users, {
 *     fields: [posts.userId],
 *     references: [users.id],
 *   }),
 * }));
 * \`\`\`
 */

`;

    // Fix import path if needed
    const fixedContent = content.replace(/from ['"]\.\/schema['"]/g, 'from "./schema.js"');

    // Prepend header comment
    const newContent = headerComment + fixedContent;
    writeFileSync(relationsPath, newContent);
    process.stdout.write('✓ Added header comment to relations.ts\n');
  } else {
    // Just fix import path if comment already exists
    const fixedContent = content.replace(/from ['"]\.\/schema['"]/g, 'from "./schema.js"');
    if (fixedContent !== content) {
      writeFileSync(relationsPath, fixedContent);
      process.stdout.write('✓ Fixed import path in relations.ts\n');
    }
  }
}

// Remove migration SQL files generated by introspect
function findSqlFiles(dir: string): string[] {
  const files: string[] = [];
  if (!existsSync(dir)) return files;

  const entries = readdirSync(dir);

  for (const entry of entries) {
    const fullPath = join(dir, entry);
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...findSqlFiles(fullPath));
    } else if (entry.endsWith('.sql')) {
      files.push(fullPath);
    }
  }

  return files;
}

findSqlFiles('./src').forEach((file) => {
  unlinkSync(file);
});

// Remove meta directory (used by Drizzle migrations, but we use Atlas)
const metaDir = './src/meta';
if (existsSync(metaDir)) {
  try {
    rmSync(metaDir, { recursive: true, force: true });
  } catch {
    // Directory might already be removed
  }
}
